spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:${SPRING_DATASOURCE_INITIALIZATION_MODE:never}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
server.servlet.session.timeout=${APP_SESSION_TIMEOUT}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
app.jwt.signing-secret=${JWT_SIGNING_SECRET}
spring.jackson.deserialization.fail-on-null-for-primitives=false
#spring.jpa.show-sql=true
